
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečen zračni tlak" ,"p","hPa", "pressure"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("minimalen zračni tlak" ,"pmin","hPa", "min pressure"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("maksimalen zračni tlak","pmax","hPa", "max pressure"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("terminska temperatura zraka na 2m","t2m_termin","°C", "termin temperature"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečna temperatura zraka na 2m","t2m","°C", "average temperature"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("minimalna temperatura zraka na 2m","t2mmin","°C", "min temperature"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("maksimalna temperatura zraka na 2m","t2mmax","°C", "max temperature"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("terminska relativna vlaga","rh_termin","%", "termin relative humidity"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečna relativna vlaga","rh","%", "average relative humidity"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("minimalna relativna vlaga","rhmin","%", "min relative humidity"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("maksimalna relativna vlaga","rhmax","%", "max relative humidity"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("količina padavin","padavine","mm", "precipitation"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečna hitrost vetra","veter_hitrost","m/s", "average wind speed"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečna smer vetra","veter_vek_smer","°", "average wind direction - true"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("maksimalna hitrost vetra","veter_max_hitrost","m/s", "max wind speed"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečen energijski tok globalnega sevanja","energija_gl","W/m2", "global radiation"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("povprečen energijski tok difuznega sevanja","energija_di","W/m2", "difused radiation"},
insert into rapids_iot.sensor_types (uuid, phenomena, uom, description) values ("UVB","energija_uvb","mW/m2", "UV radiation"}
